[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-unknown-uefi"

[profile.dev]
panic = "abort" # Disable stack unwinding on panic

[profile.release]
panic = "abort" # Disable stack unwinding on panic
