image:
  file: .gitpod.Dockerfile

ports:
# vnc
- port: 6080
# open-preview is too small to reliably use, especially on smaller viewports
  onOpen: open-browser
- port: 5900
  onOpen: ignore

tasks:
- init: ./aero.py --test --no-run
# ideally, it wouldn't build a second time
  command: ./aero.py --test
