[build]
rustc = "../sysroot/tools/host-rust/bin/rustc"
target = "x86_64-unknown-aero-system"
rustflags = ["-C", "link-args=-no-pie", "-lc"]

[target.x86_64-unknown-aero-system]
linker = "../sysroot/tools/host-gcc/bin/x86_64-aero-gcc"

[patch.crates-io]
libc = { path = "../bundled/rust-libc" }
num_cpus = { path = "../bundled/rust-num-cpus" }
users = { path = "../bundled/rust-users" }
