[package]
name = "aero_build"
version = "0.1.0"
authors = ["Joshua Price <jwpjr567@gmail.com>"]
edition = "2021"

[dependencies]
# gumdrop
# todo: set as few feature flags as required
ureq = "2.5.0"
execute = "0.2.11"
