[package]
name = "utest"
version = "0.1.0"
edition = "2021"
authors = ["Anhad Singh <andypythonappdeveloper@gmail.com>"]

[dependencies]
std = { path = "../../libs/aero_std" }
aero_syscall = { path = "../../../src/aero_syscall" }
aipc = { path = "../../libs/aipc" }
utest-proc = { path = "../utest-proc" }
