(function() {var implementors = {
"aero_kernel":[["impl <a class=\"trait\" href=\"aero_kernel/prelude/rust_2021/_core/fmt/trait.Display.html\" title=\"trait aero_kernel::prelude::rust_2021::_core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"aero_kernel/mem/paging/page/struct.AddressNotAligned.html\" title=\"struct aero_kernel::mem::paging::page::AddressNotAligned\">AddressNotAligned</a>"]],
"allocator_api2":[["impl Display for <a class=\"struct\" href=\"allocator_api2/alloc/struct.AllocError.html\" title=\"struct allocator_api2::alloc::AllocError\">AllocError</a>"],["impl&lt;T: Display + ?Sized, A: <a class=\"trait\" href=\"allocator_api2/alloc/trait.Allocator.html\" title=\"trait allocator_api2::alloc::Allocator\">Allocator</a>&gt; Display for <a class=\"struct\" href=\"allocator_api2/boxed/struct.Box.html\" title=\"struct allocator_api2::boxed::Box\">Box</a>&lt;T, A&gt;"]],
"arrayvec":[["impl&lt;const CAP: usize&gt; Display for <a class=\"struct\" href=\"arrayvec/struct.ArrayString.html\" title=\"struct arrayvec::ArrayString\">ArrayString</a>&lt;CAP&gt;"],["impl&lt;T&gt; Display for <a class=\"struct\" href=\"arrayvec/struct.CapacityError.html\" title=\"struct arrayvec::CapacityError\">CapacityError</a>&lt;T&gt;"]],
"bitflags":[["impl Display for <a class=\"struct\" href=\"bitflags/parser/struct.ParseError.html\" title=\"struct bitflags::parser::ParseError\">ParseError</a>"]],
"bytemuck":[["impl Display for <a class=\"enum\" href=\"bytemuck/enum.PodCastError.html\" title=\"enum bytemuck::PodCastError\">PodCastError</a>"],["impl Display for <a class=\"enum\" href=\"bytemuck/checked/enum.CheckedCastError.html\" title=\"enum bytemuck::checked::CheckedCastError\">CheckedCastError</a>"]],
"crabnet":[["impl Display for <a class=\"struct\" href=\"crabnet/data_link/struct.MacAddr.html\" title=\"struct crabnet::data_link::MacAddr\">MacAddr</a>"],["impl Display for <a class=\"struct\" href=\"crabnet/network/struct.Ipv4Addr.html\" title=\"struct crabnet::network::Ipv4Addr\">Ipv4Addr</a>"]],
"cursor_icon":[["impl Display for <a class=\"enum\" href=\"cursor_icon/enum.CursorIcon.html\" title=\"enum cursor_icon::CursorIcon\">CursorIcon</a>"],["impl Display for <a class=\"struct\" href=\"cursor_icon/struct.ParseError.html\" title=\"struct cursor_icon::ParseError\">ParseError</a>"]],
"hashbrown":[["impl&lt;'a, K: Debug, V: Debug, S, A: <a class=\"trait\" href=\"allocator_api2/stable/alloc/trait.Allocator.html\" title=\"trait allocator_api2::stable::alloc::Allocator\">Allocator</a>&gt; Display for <a class=\"struct\" href=\"hashbrown/hash_map/struct.OccupiedError.html\" title=\"struct hashbrown::hash_map::OccupiedError\">OccupiedError</a>&lt;'a, K, V, S, A&gt;"]],
"log":[["impl Display for <a class=\"enum\" href=\"log/enum.LevelFilter.html\" title=\"enum log::LevelFilter\">LevelFilter</a>"],["impl Display for <a class=\"struct\" href=\"log/struct.SetLoggerError.html\" title=\"struct log::SetLoggerError\">SetLoggerError</a>"],["impl Display for <a class=\"struct\" href=\"log/struct.ParseLevelError.html\" title=\"struct log::ParseLevelError\">ParseLevelError</a>"],["impl Display for <a class=\"enum\" href=\"log/enum.Level.html\" title=\"enum log::Level\">Level</a>"]],
"num_traits":[["impl Display for <a class=\"struct\" href=\"num_traits/struct.ParseFloatError.html\" title=\"struct num_traits::ParseFloatError\">ParseFloatError</a>"]],
"raw_cpuid":[["impl Display for <a class=\"struct\" href=\"raw_cpuid/struct.SoCVendorBrand.html\" title=\"struct raw_cpuid::SoCVendorBrand\">SoCVendorBrand</a>"],["impl Display for <a class=\"struct\" href=\"raw_cpuid/struct.VendorInfo.html\" title=\"struct raw_cpuid::VendorInfo\">VendorInfo</a>"],["impl Display for <a class=\"enum\" href=\"raw_cpuid/enum.CacheType.html\" title=\"enum raw_cpuid::CacheType\">CacheType</a>"],["impl Display for <a class=\"struct\" href=\"raw_cpuid/struct.CacheInfo.html\" title=\"struct raw_cpuid::CacheInfo\">CacheInfo</a>"],["impl Display for <a class=\"enum\" href=\"raw_cpuid/enum.ExtendedRegisterStateLocation.html\" title=\"enum raw_cpuid::ExtendedRegisterStateLocation\">ExtendedRegisterStateLocation</a>"],["impl Display for <a class=\"enum\" href=\"raw_cpuid/enum.DatType.html\" title=\"enum raw_cpuid::DatType\">DatType</a>"],["impl Display for <a class=\"enum\" href=\"raw_cpuid/enum.Associativity.html\" title=\"enum raw_cpuid::Associativity\">Associativity</a>"],["impl Display for <a class=\"enum\" href=\"raw_cpuid/enum.TopologyType.html\" title=\"enum raw_cpuid::TopologyType\">TopologyType</a>"],["impl Display for <a class=\"enum\" href=\"raw_cpuid/enum.ExtendedRegisterType.html\" title=\"enum raw_cpuid::ExtendedRegisterType\">ExtendedRegisterType</a>"]],
"rustc_demangle":[["impl&lt;'a&gt; Display for <a class=\"struct\" href=\"rustc_demangle/struct.Demangle.html\" title=\"struct rustc_demangle::Demangle\">Demangle</a>&lt;'a&gt;"]],
"serde":[["impl&lt;'a&gt; Display for <a class=\"enum\" href=\"serde/de/enum.Unexpected.html\" title=\"enum serde::de::Unexpected\">Unexpected</a>&lt;'a&gt;"],["impl&lt;'a&gt; Display for dyn <a class=\"trait\" href=\"serde/de/trait.Expected.html\" title=\"trait serde::de::Expected\">Expected</a> + 'a"],["impl Display for <a class=\"struct\" href=\"serde/de/value/struct.Error.html\" title=\"struct serde::de::value::Error\">Error</a>"]],
"serde_json":[["impl Display for <a class=\"struct\" href=\"serde_json/struct.Error.html\" title=\"struct serde_json::Error\">Error</a>"],["impl Display for <a class=\"struct\" href=\"serde_json/value/struct.Number.html\" title=\"struct serde_json::value::Number\">Number</a>"],["impl Display for <a class=\"enum\" href=\"serde_json/enum.Value.html\" title=\"enum serde_json::Value\">Value</a>"]],
"spin":[["impl&lt;'a, T: ?Sized + Display&gt; Display for <a class=\"struct\" href=\"spin/mutex/spin/struct.SpinMutexGuard.html\" title=\"struct spin::mutex::spin::SpinMutexGuard\">SpinMutexGuard</a>&lt;'a, T&gt;"],["impl&lt;'rwlock, T: ?Sized + Display, R&gt; Display for <a class=\"struct\" href=\"spin/rwlock/struct.RwLockUpgradableGuard.html\" title=\"struct spin::rwlock::RwLockUpgradableGuard\">RwLockUpgradableGuard</a>&lt;'rwlock, T, R&gt;"],["impl&lt;'rwlock, T: ?Sized + Display&gt; Display for <a class=\"struct\" href=\"spin/rwlock/struct.RwLockReadGuard.html\" title=\"struct spin::rwlock::RwLockReadGuard\">RwLockReadGuard</a>&lt;'rwlock, T&gt;"],["impl&lt;'a, T: ?Sized + Display&gt; Display for <a class=\"struct\" href=\"spin/mutex/struct.MutexGuard.html\" title=\"struct spin::mutex::MutexGuard\">MutexGuard</a>&lt;'a, T&gt;"],["impl&lt;'rwlock, T: ?Sized + Display, R&gt; Display for <a class=\"struct\" href=\"spin/rwlock/struct.RwLockWriteGuard.html\" title=\"struct spin::rwlock::RwLockWriteGuard\">RwLockWriteGuard</a>&lt;'rwlock, T, R&gt;"]],
"vte":[["impl Display for <a class=\"struct\" href=\"vte/ansi/struct.Rgb.html\" title=\"struct vte::ansi::Rgb\">Rgb</a>"]],
"xmas_elf":[["impl Display for dyn <a class=\"trait\" href=\"xmas_elf/symbol_table/trait.Entry.html\" title=\"trait xmas_elf::symbol_table::Entry\">Entry</a>"],["impl&lt;'a&gt; Display for <a class=\"enum\" href=\"xmas_elf/header/enum.HeaderPt2.html\" title=\"enum xmas_elf::header::HeaderPt2\">HeaderPt2</a>&lt;'a&gt;"],["impl Display for <a class=\"struct\" href=\"xmas_elf/program/struct.ProgramHeader64.html\" title=\"struct xmas_elf::program::ProgramHeader64\">ProgramHeader64</a>"],["impl&lt;'a&gt; Display for <a class=\"enum\" href=\"xmas_elf/sections/enum.SectionHeader.html\" title=\"enum xmas_elf::sections::SectionHeader\">SectionHeader</a>&lt;'a&gt;"],["impl&lt;'a&gt; Display for <a class=\"struct\" href=\"xmas_elf/header/struct.Header.html\" title=\"struct xmas_elf::header::Header\">Header</a>&lt;'a&gt;"],["impl Display for <a class=\"struct\" href=\"xmas_elf/program/struct.ProgramHeader32.html\" title=\"struct xmas_elf::program::ProgramHeader32\">ProgramHeader32</a>"],["impl&lt;P: Display&gt; Display for <a class=\"struct\" href=\"xmas_elf/header/struct.HeaderPt2_.html\" title=\"struct xmas_elf::header::HeaderPt2_\">HeaderPt2_</a>&lt;P&gt;"],["impl&lt;'a&gt; Display for <a class=\"enum\" href=\"xmas_elf/program/enum.ProgramHeader.html\" title=\"enum xmas_elf::program::ProgramHeader\">ProgramHeader</a>&lt;'a&gt;"],["impl Display for <a class=\"struct\" href=\"xmas_elf/program/struct.Flags.html\" title=\"struct xmas_elf::program::Flags\">Flags</a>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()